"""Tests for papyrik.core.document.PdfDocument.

Covers the three failure modes CLAUDE.md calls out - open, corrupt-file
handling, encrypted-file detection - plus dirty tracking and rendering.

Fixtures are generated by tests/make_fixtures.py; this module regenerates them
automatically if they are missing.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

from papyrik.core.document import (
    PdfCorruptError,
    PdfDocument,
    PdfEncryptedError,
    is_encrypted,
)
from tests import make_fixtures

FIXTURES = make_fixtures.FIXTURES
PASSWORD = make_fixtures.ENCRYPTED_PASSWORD


def _fixture(name: str) -> Path:
    path = FIXTURES / name
    if not path.exists():
        make_fixtures.main()
    return path


# -- open ----------------------------------------------------------------

def test_open_reports_page_count():
    with PdfDocument(_fixture("large_300p.pdf")) as doc:
        assert doc.is_open
        assert doc.page_count == 300


def test_open_simple_document():
    with PdfDocument(_fixture("cjk.pdf")) as doc:
        assert doc.page_count == 1


def test_close_makes_document_unusable():
    doc = PdfDocument(_fixture("cjk.pdf"))
    doc.close()
    assert not doc.is_open
    with pytest.raises(Exception):
        _ = doc.page_count


def test_missing_file_raises_corrupt():
    with pytest.raises(PdfCorruptError):
        PdfDocument(FIXTURES / "does_not_exist.pdf")


# -- corrupt-file handling -----------------------------------------------

def test_corrupt_file_raises_corrupt():
    with pytest.raises(PdfCorruptError):
        PdfDocument(_fixture("corrupt.pdf"))


def test_is_encrypted_on_corrupt_raises_corrupt():
    with pytest.raises(PdfCorruptError):
        is_encrypted(_fixture("corrupt.pdf"))


# -- encrypted-file detection --------------------------------------------

def test_is_encrypted_true_for_encrypted():
    assert is_encrypted(_fixture("encrypted.pdf")) is True


def test_is_encrypted_false_for_plain():
    assert is_encrypted(_fixture("cjk.pdf")) is False


def test_encrypted_without_password_raises():
    with pytest.raises(PdfEncryptedError):
        PdfDocument(_fixture("encrypted.pdf"))


def test_encrypted_with_wrong_password_raises():
    with pytest.raises(PdfEncryptedError):
        PdfDocument(_fixture("encrypted.pdf"), password="wrong")


def test_encrypted_with_correct_password_opens():
    with PdfDocument(_fixture("encrypted.pdf"), password=PASSWORD) as doc:
        assert doc.page_count == 1


# -- rendering -----------------------------------------------------------

def test_render_png_returns_png_bytes():
    with PdfDocument(_fixture("scanned.pdf")) as doc:
        data = doc.render_png(0)
    assert data[:8] == b"\x89PNG\r\n\x1a\n"


def test_render_png_out_of_range():
    with PdfDocument(_fixture("cjk.pdf")) as doc:
        with pytest.raises(IndexError):
            doc.render_png(5)


def test_thumbnail_returns_bounded_pixmap():
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    from PyQt6.QtWidgets import QApplication

    app = QApplication.instance() or QApplication(sys.argv)
    with PdfDocument(_fixture("scanned.pdf")) as doc:
        pixmap = doc.thumbnail(0, max_dim=200)
    assert not pixmap.isNull()
    assert max(pixmap.width(), pixmap.height()) <= 200
    _ = app  # keep reference alive for the duration of the test
